/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_sevenzip_SevenZip_Format */

#ifndef _Included_net_sf_sevenzip_SevenZip_Format
#define _Included_net_sf_sevenzip_SevenZip_Format
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
