/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_sevenzip_SevenZip */

#ifndef _Included_net_sf_sevenzip_SevenZip
#define _Included_net_sf_sevenzip_SevenZip
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_sevenzip_SevenZip
 * Method:    openArchive
 * Signature: (Ljava/lang/String;)Lnet/sf/sevenzip/SevenZip;
 */
JNIEXPORT jobject JNICALL Java_net_sf_sevenzip_SevenZip_openArchive
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_sf_sevenzip_SevenZip
 * Method:    initSevenZipLibrary
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_sevenzip_SevenZip_initSevenZipLibrary
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
