
INCLUDE(FindJava)
INCLUDE(FindJNI)

IF (JAVA_COMPILE)
    GET_FILENAME_COMPONENT(JAVA_BIN_PATH ${JAVA_COMPILE} PATH)
    FIND_PROGRAM(JAVA_JAVAH javah ${JAVA_BIN_PATH})
ENDIF(JAVA_COMPILE)

MARK_AS_ADVANCED(JAVA_JAVAH)
