IF(WIN32 OR WIN64)
    IF (CMAKE_SYSTEM_NAME MATCHES "CYGWIN.*")
        # CygWin
        FIND_FILE(MINWGM10_DLL_FILENAME "mingwm10.dll" $ENV{PATH})
    ELSE(CMAKE_SYSTEM_NAME MATCHES "CYGWIN.*")
        # MinGW
    ENDIF(CMAKE_SYSTEM_NAME MATCHES "CYGWIN.*")
    MARK_AS_ADVANCED(MINWGM10_DLL_FILENAME)
ENDIF(WIN32 OR WIN64)
